name = "UnconditionalSchauderBasis"
version = "0.1.4"
keywords = ["math"]
defaultTargets = ["UnconditionalSchauderBasis"]

releaseRepo = "https://github.com/SmaniaD/UnconditionalSchauderBasis"
preferReleaseBuild = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
 

[[lean_lib]]
name = "UnconditionalSchauderBasis"